name: Turnstile
main: com.codisimus.turnstile.TurnstileMain
version: 3.0.0
author: Codisimus
website: www.codisimus.com
description: Charge players money/items to enter an area
startup: postworld
softdepend: [Vault, Citizens2]
commands:
  ts:
    description: Used to setup and manage Turnstiles
    usage: /<command> help
permissions:
  turnstile.open:
    description: Needed to open a Turnstile
  turnstile.sign:
    description: Needed to make a Turnstile Sign
  turnstile.make:
    description: Needed to make a Turnstile (/ts make)
  turnstile.set.price:
    description: Needed to set the price of a Turnstile (/ts price)
  turnstile.set.nofraud:
    description: Needed to change whether a Turnstile is in NoFraud mode (/ts nofraud)
  turnstile.set.owner:
    description: Needed to the owner of a Turnstile (/ts owner)
  turnstile.set.access:
    description: Needed to set who has access to a Turnstile (/ts access)
  turnstile.set.bank:
    description: Needed to set the bank that a Turnstile is connected to (/ts bank)
  turnstile.set.free:
    description: Needed to set the time that a Turnstile is free (/ts free)
  turnstile.set.locked:
    description: Needed to set the time that a Turnstile is locked (/ts locked)
  turnstile.earned:
    description: Needed to see how much a Turnstile has earned (/ts earned)
  turnstile.collect:
    description: Needed to collect money/items from a Turnstile (/ts collect)
  turnstile.list:
    description: Needed to see a list of Turnstiles (/ts list)
  turnstile.info:
    description: Needed to See info about a Turnstile (/ts info)
  turnstile.openfree:
    description: Open Turnstiles free of charge
  turnstile.ignoreowner:
    description: Edit other Players' Turnstiles